name: Render & Deploy Quarto Book

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ① Install Quarto CLI
      - uses: quarto-dev/quarto-actions/setup@v2

     # ② Install Python 3 and Jupyter/nbformat
      - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
      - name: Install Jupyter & deps
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbformat ipykernel

      # ③ Render book & push to gh-pages
      - name: Render & Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}