name: Render & Deploy Quarto Book

on:
  push:
    branches: [main]      # rebuild on every push to main
  workflow_dispatch:      # run-button in the Actions UI

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # 1 Check out source
      - uses: actions/checkout@v4

      # 2 Install Quarto CLI
      - uses: quarto-dev/quarto-actions/setup@v2

      # 3 Set up Python + Jupyter so notebooks render
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Jupyter & deps
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbformat ipykernel

      # 4 Render the book & publish to the gh-pages branch
      - name: Render & Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}