name: Render & Deploy Quarto Book

on:
  push:
    branches: [main]          # rebuild on every push
  workflow_dispatch:          # manual “Run” button

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # 1  Check out your source code
      - uses: actions/checkout@v4

      # 2  Install Quarto CLI
      - uses: quarto-dev/quarto-actions/setup@v2

      # 3  Set up Python *and* every library your notebooks import
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Jupyter & notebook dependencies
        run: |
          python -m pip install --upgrade pip
          # core notebook runtime
          pip install jupyter nbformat ipykernel
          # scientific stack your notebooks use
          pip install numpy pandas matplotlib scikit-learn seaborn plotly geopandas contextily folium ipywidgets shapely
      # 4 ── Render the book **and** copy .nojekyll into _site/, then push
      - name: Render & Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          postprocess: |
            # Quarto has finished rendering into _site/ at this point
            cp .nojekyll _site/.nojekyll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}